services:
  kagglecv:
    build: .
    image: kagglecv:gpu
    container_name: kagglecv_gpu
    working_dir: /app
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./outputs:/app/outputs
    shm_size: "8gb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: bash